### ISSUE TITLE
Chante the starting page

### ISSUE THREAD

**Issue by ivanjimenez** [acgtyrant/hexo-theme-tyrant#1]
I'd like changing the start page in my hexo blog, so, I want to show "archives" page instead "home" page. I have to change app.js to write a new route? Or I can make this in de _config.yml?

Thanks!

**Comment by acgtyrant** [comment]
@ivanjimenez Hi, sorry for I am not good at this. You can ask the creator of hexo [here](https://github.com/tommy351/hexo), I think he will reply to you quickly.

**Comment by ivanjimenez** [comment]
Sorry about this! I will ask him for it! 
Thank you for your support.
Cheers.
