### ISSUE TITLE
Home页面不出现“Read More”按钮

### ISSUE THREAD

**Issue by will-yim** [acgtyrant/hexo-theme-tyrant#4]
在Home页面应该只显示文章摘要，但是使用light主题的Home页把文章全部都显示出来，没有“Read More”这类excerpt_link，是哪里没设置好吗？比如您这个页面：http://arch.acgtyrant.com/

**Comment by acgtyrant** [comment]
试试这个：[Hexo 自动添加 ReadMore 标记](http://twiceyuan.com/2014/05/25/hexo%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0readmore%E6%A0%87%E8%AE%B0/)

**Comment by will-yim** [comment]
非常感谢
